[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run startServer"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"

# Cron service specific settings
[services.cron-crawler]
startCommand = "curl -X POST $MAIN_SERVICE_URL/api/crawl/start-all -H 'Content-Type: application/json'"
schedule = "0 */2 * * *" 