[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run startServer"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"

