[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "docker-entrypoint.sh postgres"

[variables]
POSTGRES_DB = "railway"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "secure_random_password_123"
PGDATA = "/var/lib/postgresql/data/pgdata"