[build]
builder = "nixpacks"
buildCommand = "echo 'Skipping build for cron service'"
ignoreBuildCommand = true

[deploy]
startCommand = "curl -X POST $MAIN_SERVICE_URL/api/crawl/start-all -H 'Content-Type: application/json'"
restartPolicyType = "never"
ignoreProcfile = true

[cron]
schedule = "0 */2 * * *" 